# Clasification with PySpark

Los modelos de clasificación pueden usarse para resolver distintos problemas:

 * Predecir la probabilidad de que un usuario seleccione un anuncio de internet (selecciona o no selecciona)
 * Detectar fraude (fraude o no fraude)
 * clasificar imagenes en categorias, clases o etiquetas (multiclase)
 * Asignar categorias a articulos de noticias, paginas de internet y opiniones.
 
 Para este ejemplo usaremos el [Kaggle StumpleUpon evergreen dataset](https://www.kaggle.com/c/stumbleupon/data)

In [2]:
path = "/Users/user/GitHub/PySpark-Notes/StumpleUponEvergreen/train.tsv"
raw_data = sc.textFile(path)
num_data = raw_data.count()
records = raw_data.map(lambda x: x.split('\t"'))
first = records.first()
print first


[u'"url"', u'urlid"', u'boilerplate"', u'alchemy_category"', u'alchemy_category_score"', u'avglinksize"', u'commonlinkratio_1"', u'commonlinkratio_2"', u'commonlinkratio_3"', u'commonlinkratio_4"', u'compression_ratio"', u'embed_ratio"', u'framebased"', u'frameTagRatio"', u'hasDomainLink"', u'html_ratio"', u'image_ratio"', u'is_news"', u'lengthyLinkDomain"', u'linkwordscore"', u'news_front_page"', u'non_markup_alphanum_characters"', u'numberOfLinks"', u'numwords_in_url"', u'parametrizedLinkRatio"', u'spelling_errors_ratio"', u'label"']


In [3]:
text_file = sc.textFile('/Users/user/GitHub/PySpark-Notes/StumpleUponEvergreen/train.tsv')
#text_file.collect()

In [4]:
import pandas as pd

df = pd.read_csv('/Users/user/GitHub/PySpark-Notes/StumpleUponEvergreen/train.tsv', sep = '"	"')
                 #, names = ['url','urlid','boilerplate',\
                  #          'alchemy_category','alchemy_category_score','avglinksize',\
                   #         'commonlinkratio_1','commonlinkratio_2','commonlinkratio_3',\
                    #        'commonlinkratio_4','compression_ratio','embed_ratio'\
                     #       ,'framebased','frameTagRatio','hasDomainLink'\
                      #      ,'html_ratio','image_ratio','is_news','lengthyLinkDomain',\
                       #     'linkwordscore','news_front_page','non_markup_alphanum_characters'\
                        #    ,'numberOfLinks','numwords_in_url','parametrizedLinkRatio'\
                         #   ,'spelling_errors_ratio','label'])
df

/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:3: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators; you can avoid this warning by specifying engine='python'.
  app.launch_new_instance()


"url  urlid  \
0     "http://www.bloomberg.com/news/2010-12-23/ibm-...   4042   
1     "http://www.popsci.com/technology/article/2012...   8471   
2     "http://www.menshealth.com/health/flu-fighting...   1164   
3     "http://www.dumblittleman.com/2007/12/10-foolp...   6684   
4     "http://bleacherreport.com/articles/1205138-th...   9006   
5     "http://www.conveniencemedical.com/genital-her...   7018   
6     "http://gofashionlane.blogspot.tw/2012/06/amer...   8685   
7     "http://www.insidershealth.com/article/racing_...   3402   
8     "http://www.valetmag.com/the-handbook/features...    477   
9     "http://www.howsweeteats.com/2010/03/24/cookie...   6731   
10                             "http://www.reuters.com/   2293   
11    "http://www.midwestsportsfans.com/2010/12/phot...   3651   
12    "http://www.ivillage.com/our-dirty-mouths/4-b-...   1917   
13    "http://www.thedailygreen.com/print-this/healt...   1063   
14    "http://www.phillyburbs.com/blogs/type-a-kitch...   2110   
15    "http://sportsillustrated.cnn.com/2012_swimsui...   5318   
16    "http://theawesomer.com/liquid-mountaineering/...   9842   
17    "http://www.guardian.co.uk/fashion/gallery/201...   3946   
18    "http://sugarcrafter.net/2011/06/06/grilled-pe...    334   
19    "http://www.ivillage.com/bathroom-degrunge-you...    271   
20    "http://www.tmz.com/2012/12/20/olympic-soccer-...   6984   
21    "http://www.bbc.co.uk/food/recipes/blueberry_a...   8979   
22          "http://www.quitcounter.com/quitsmoking.php   1502   
23    "http://www.monicel.info/2008/08/03/original-t...   8945   
24    "http://blogs.babble.com/family-kitchen/2011/0...   2839   
25    "http://www.midwestsportsfans.com/2010/10/earl...   1499   
26                        "http://breakingnewsblog.com/   7298   
27    "http://www.naffziger.net/blog/2008/07/05/the-...   3294   
28    "http://humor.cool-been.com/wp/supermodels-sho...   2949   
29    "http://sportsillustrated.cnn.com/2011_swimsui...   4156   
...                                                 ...    ...   
7365                 "http://cheezburger.com/6631333376  10446   
7366     "http://www.newsweek.com/id/43884/output/print   8329   
7367  "http://ca.askmen.com/sports/foodcourt_250/253...   6416   
7368  "http://www.cafejohnsonia.com/2011/08/sourdoug...   8442   
7369  "http://noblepig.com/2009/05/10/just-amazing.aspx   7202   
7370  "http://www.nastygal.com/clothes/fancy-knot-dress   8563   
7371  "http://betterinbulk.net/2012/10/perfect-pumpk...   9192   
7372  "http://dornob.com/get-the-lead-out-cartridge-...   3566   
7373                           "http://blog.khymos.org/   3788   
7374  "http://www.guardian.co.uk/fashion/gallery/201...   7485   
7375                  "http://www.whatmegansmaking.com/   7425   
7376               "http://www.chinesefood-recipes.com/   4572   
7377  "http://www.forbes.com/sites/greatspeculations...  10509   
7378  "http://www.foodnetwork.com/recipes-and-cookin...   5183   
7379  "http://www.savoringthethyme.com/2011/08/toast...   7696   
7380  "http://m.ivillage.com/wicked-good-chocolate-p...   1823   
7381                      "http://www.caravanstyle.com/   4475   
7382  "http://www.allthingscupcake.com/2007/12/05/mo...   8327   
7383                 "http://randomrr.com/80s-kids.html  10126   
7384  "http://iammommy.typepad.com/i_am_baker/2011/0...   1061   
7385  "http://shopmarkethq.com/collections/brands-mi...   5419   
7386  "http://slice.seriouseats.com/archives/2010/06...    546   
7387  "http://achicdirection.com/2012/01/23/vintage-...  10382   
7388  "http://www.villagevoice.com/bestof/2009/award...   7634   
7389  "http://www.worth1000.com/emailthis.asp?entry=...   8923   
7390  "http://techcrunch.com/2010/09/08/kno-raises-4...   8958   
7391  "http://www.uncoached.com/category/why-i-miss-...   8895   
7392  "http://eatthis.menshealth.com/slide/sweet-pot...   1191   
7393                         "http://naturallyella.com/   5612   
7394  "http://sportsillus

In [5]:
df.count()

"url                              7395
urlid                             7395
boilerplate                       7395
alchemy_category                  7395
alchemy_category_score            7395
avglinksize                       7395
commonlinkratio_1                 7395
commonlinkratio_2                 7395
commonlinkratio_3                 7395
commonlinkratio_4                 7395
compression_ratio                 7395
embed_ratio                       7395
framebased                        7395
frameTagRatio                     7395
hasDomainLink                     7395
html_ratio                        7395
image_ratio                       7395
is_news                           7395
lengthyLinkDomain                 7395
linkwordscore                     7395
news_front_page                   7395
non_markup_alphanum_characters    7395
numberOfLinks                     7395
numwords_in_url                   7395
parametrizedLinkRatio             7395
spelling_errors_ratio    

In [6]:
#sacamos un feature de categorias

print df['alchemy_category']

0                 business
1               recreation
2                   health
3                   health
4                   sports
5                        ?
6       arts_entertainment
7                        ?
8                        ?
9                        ?
10                business
11                  sports
12                  health
13                       ?
14              recreation
15              recreation
16              recreation
17      arts_entertainment
18              recreation
19                  health
20                  sports
21              recreation
22                  health
23                       ?
24                       ?
25                  sports
26                  sports
27                business
28                       ?
29                       ?
               ...        
7365                     ?
7366                     ?
7367                     ?
7368                     ?
7369                     ?
7370            recreation
7

In [7]:
categories = sorted(df['alchemy_category'].unique().tolist())
print 'De la columna que nos interesa, regresamos las \
diferentes ocupaciones y los pasamos a una lista:\n\n', categories

De la columna que nos interesa, regresamos las diferentes ocupaciones y los pasamos a una lista:

['?', 'arts_entertainment', 'business', 'computer_internet', 'culture_politics', 'gaming', 'health', 'law_crime', 'recreation', 'religion', 'science_technology', 'sports', 'unknown', 'weather']


In [9]:
def category_features_vectorizer(df_name,column_name):    
    
    all_categories = sorted(df_name[column_name].unique().tolist())
    #print 'These are the categories:\n',all_categories
    
    
    idx = 0
    all_categories_dict = {}
    
    for categories in all_categories:
        all_categories_dict[categories] = idx
        idx +=1
    
    import numpy as np
    k = len(all_categories_dict)
    binary_x = np.zeros(k)
    for item in all_categories:
        k_category = all_categories_dict[item]
        for item_2 in [k_category]:
            binary_x[item_2] = 1
            print binary_x
            
    
    
category_features_vectorizer(df,'alchemy_category')


[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 1.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 1.  1.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 1.  1.  1.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 1.  1.  1.  1.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 1.  1.  1.  1.  1.  1.  1.  0.  0.  0.  0.  0.  0.  0.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  0.  0.  0.  0.  0.  0.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  0.  0.  0.  0.  0.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.  0.  0.  0.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.  0.  0.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.  0.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


In [87]:
def category_features_vectorizer(df_name,column_name):
    
    all_categories = sorted(df_name[column_name].unique().tolist())
    #print 'These are the categories:\n',all_categories
    idx = 0
    all_categories_dict = {}
    
    for categories in all_categories:
        all_categories_dict[categories] = idx
        idx +=1
        
    import numpy as np
    k = len(all_categories_dict)
    binary_x = np.zeros(k)
    
    for item in all_categories:
        k_category = all_categories_dict[item]
        for item_2 in [k_category]:
            binary_x[item_2] = 1
            print binary_x
            
            

    
category_features_vectorizer(df,'alchemy_category')


[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 1.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 1.  1.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 1.  1.  1.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 1.  1.  1.  1.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 1.  1.  1.  1.  1.  1.  1.  0.  0.  0.  0.  0.  0.  0.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  0.  0.  0.  0.  0.  0.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  0.  0.  0.  0.  0.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.  0.  0.  0.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.  0.  0.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.  0.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
